### ISSUE TITLE
Adicionar testes

### ISSUE THREAD

**Issue by IvoPereira** [devpt-org/welcome-bot#21]
O projeto atual deveria ter uma pipeline de testes implementada.

Sugeria utilizarmos jest tendo em conta ser o mais consensual em JavaScript, mas estou aberto a ideias.

**Comment by ivoencarnacao** [comment]
Há possibilidade de usar o https://vitest.dev/ ?

**Comment by IvoPereira** [comment]
Não conhecia mas parece-me bem, não vejo qualquer problema @ivoencarnacao.
