### ISSUE TITLE
Converter para TypeScript

### ISSUE THREAD

**Issue by IvoPereira** [devpt-org/welcome-bot#22]
O projeto e a developer experience beneficiariam das tipagens e do acesso a funcionalidades de ES6 e ES7 fornecidas pelo TypeScript.

Tendo em conta o tamanho do projeto ser ainda bastante reduzido, penso que seria uma boa altura para a conversão da tecnologia.

**Comment by ivoencarnacao** [comment]
Acho que deveríamos manter em JavaScript por enquanto, de forma a abranger uma maior parte da comunidade.

Eventualmente poderíamos fazer um case-study com a reconversão para TypeScript.

**Comment by gustavos00** [comment]
Olá, 
Tal como falado, é para continuar com este issue. Sendo assim, vou iniciar o desenvolvimento 🥳

**Comment by IvoPereira** [comment]
Closed by #44.
