### ISSUE TITLE
Remover a dependência do filesystem do Node

### ISSUE THREAD

**Issue by ivoencarnacao** [devpt-org/welcome-bot#29]
Se colocássemos as frases num ficheiro .js, poderíamos remover esta dependência.

**Comment by IvoPereira** [comment]
Por mim parece-me bem, não estou a ver nenhum problema.

Podes criar PR?

**Comment by t-var-s** [comment]
Acho que sim, peguei neste issue. Deixa na mesma a função async só para o caso de alguém querer fazer outra coisa entretanto.

**Comment by IvoPereira** [comment]
Implementado no #31.
