### ISSUE TITLE
PROBLEMAS GRAVES

### ISSUE THREAD

**Issue by JoaoOliveiraRocha** [devpt-org/welcome-bot#8]
Quais são os caracteres disponíveis para este bot? Unicode? discord markdown?

Já agora, para além do `<@${context.params.event.user.id}>` temos mais alguma tag? como por exemplo hora de entrada? Seria engraçado dizer a alguém que entrasse às 16:30 que o giveaway de uma 3070 foi às 16:24 por exemplo

**Comment by IvoPereira** [comment]
A mensagem construída deve ter no máximo 2000 carateres. E suporta Discord markdown sim. É literalmente uma mensagem que é enviada para a API do Discord.

Por enquanto não temos nenhuma tag extra, mas é uma excelente ideia.

Vou ver se tenho tempo para pôr o projeto open-source.

Qualquer dúvida fica à vontade para reabrir o issue.
